#! /bin/sh -e
## Ye Olde Debian Archive Control Kit -- a CLI for dak commands
## Copyright (C) 2012  Gergely Nagy <algernon@debian.org>
##
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program.  If not, see <http://www.gnu.org/licenses/>.

VERSION="0~0"

set -e

usage () {
        if ! man -w yodack >/dev/null 2>/dev/null; then
                for p in "$(dirname $0)" "$(dirname $(realpath $0 2>/dev/null) 2>/dev/null)"; do
                        MANPATH="$p"
                        export MANPATH
                        if man -w yodack >/dev/null 2>/dev/null; then
                                break
                        fi
                done
        fi
        man yodack
        exit 0
}

## --- Default file locations --- ##

yodack_dir="$(mktemp -d)"
yodack_out="${yodack_dir}/${USER}-$(date +%s).tmp"
yodack_final="${yodack_dir}/${USER}-$(date +%s).dak-commands"

## --- Helpers --- ##

yodack_arg_strip () {
        echo "$1" | sed -e "s#^[        ,.;]*##g" \
                        -e "s#[         ,.;]*\$##g"
}

yodack_fatal () {
        echo "$@" >&2
        yodack_cleanup
        exit 1
}

yodack_target_sanitise () {
        echo "$@" | sed -e "s/[^A-Za-z0-9_]/_/g"
}

yodack_cleanup () {
        rm -rf "${yodack_dir}"
}

trap yodack_cleanup 0
trap yodack_cleanup INT QUIT ABRT

## --- Add stuff to the output --- ##

yodack_add_comments () {
        cat >>"${yodack_out}" <<EOF

# A dak command file this was, great responsibility it has.
#  - Yodack ${VERSION}
EOF
}

yodack_add_archive () {
        if [ -z "$1" ]; then
                return
        fi
        if [ -e "${yodack_out}" ]; then
                echo >>"${yodack_out}"
        fi

        m="${DEBEMAIL:-${EMAIL:-${USER}@$(hostname -f)}}"
        if [ -z "${DEBFULLNAME}" ] && [ -z "${NAME}" ]; then
                uploader="${m}"
        else
                uploader="${DEBFULLNAME:-${NAME}} <${m}>"
        fi

        cat >>"${yodack_out}" <<EOF
Archive: $1
Uploader: ${uploader}

EOF
}

yodack_add_action () {
        if [ -z "$1" ]; then
                return
        fi
        cat >>"${yodack_out}" <<EOF

Action: $1
EOF
}

yodack_add_dm_fingerprint () {
        if fprs=$(gpg --no-options --no-default-keyring \
                      --keyring "$2" \
                      --list-options no-show-photo --fingerprint "$1" 2>/dev/null); then
                :
        else
                yodack_fatal "A known DM permissions to set, you must."
        fi

        key_count="$(echo "$fprs" | grep -c "^pub")"
        if [ "${key_count}" -ne 1 ]; then
                yodack_fatal "A DM describe better, you must. These, I know, choose one wisely:

$fprs"
        fi

        fpr="$(echo "$fprs" | grep "Key fingerprint =" | sed -e "s,.*Key fingerprint = ,,")"

        cat >>"${yodack_out}" <<EOF
Fingerprint: $fpr
EOF
}

yodack_add_dm_allow () {
        if [ -z "$1" ]; then
                return
        fi
        cat >>"${yodack_out}" <<EOF
Allow:$1
EOF
}

yodack_add_dm_deny () {
        if [ -z "$1" ]; then
                return
        fi
        cat >>"${yodack_out}" <<EOF
Deny:$1
EOF
}

yodack_add_section_end () {
        echo >>"${yodack_out}"
}

## --- Command line parsing --- ##

yodack_parse_argv_archive () {
        set -- $@

        while [ $# -gt 0 ]; do
                case "$1" in
                        "for"|"at"|"on"|"then"|"also"|"furthermore"|"please"|"do")
                                ;;
                        *)
                                archive="$(yodack_arg_strip $1)"
                                break
                                ;;
                esac
                shift
        done
        if [ -z "${archive}" ]; then
                yodack_fatal "No archive you give? Yodack nothing can do."
        fi
        yodack_add_archive "${archive}"

        shift
        echo "$@"
}

yodack_parse_argv_action () {
        set -- $@

        while [ $# -gt 0 ]; do
                case "$1" in
                        "do"|"on"|"at"|"for"|"please"|"also"|"then"|"furthermore")
                                ;;
                        *)
                                action="$(yodack_arg_strip $1)"
                                break
                                ;;
                esac
                shift
        done

        if [ -z "${action}" ]; then
                yodack_fatal "To do what, you tell me, or Yodack no do anything."
        fi

        case "${action}" in
                "dm"|"debian-maintainer")
                        argv="$(yodack_parse_argv_action_dm $@)"
                        ;;
                "debian")
                        if [ "$2" = "maintainer" ]; then
                                shift
                                argv="$(yodack_parse_argv_action_dm $@)"
                        else
                                argv="$(yodack_parse_argv_action_generic $@)"
                        fi
                        ;;
                *)
                        argv="$(yodack_parse_argv_action_generic $@)"
                        ;;
        esac

        echo "$argv"
}

yodack_parse_argv_action_dm () {
        set -- $@

        shift
        keyid="$(yodack_arg_strip $1)"
        shift

        stop=0
        allow=0
        deny=0
        keyring=/usr/share/keyrings/debian-maintainers.gpg

        while [ $# -gt 0 ] && [ "$stop" -eq 0 ]; do
                case "$1" in
                        *"."|*";")
                                stop=1
                                ;;
                esac
                case "$1" in
                        "please"|"upload"|"of"|"package"|"but"|"also"|"or"|"packages"|"uploads"|"uploading"|"rights"|"to"|"permission"|"permissions"|"on"|"in"|"for")
                                ;;
                        "allow"|"grant")
                                allow=1
                                deny=0
                                ;;
                        "deny"|"disallow"|"forbid"|"revoke")
                                deny=1
                                allow=0
                                ;;
                        "keyring")
                                keyring="$2"
                                shift
                                ;;
                        *)
                                if [ "$allow" -eq 1 ]; then
                                        allow_list="${allow_list} $(yodack_arg_strip $1)"
                                elif [ "$deny" -eq 1 ]; then
                                        deny_list="${deny_list} $(yodack_arg_strip $1)"
                                else
                                        yodack_fatal "Confused, I am."
                                fi
                                ;;
                esac
                shift
        done

        yodack_add_action "dm"
        yodack_add_dm_fingerprint "${keyid}" "${keyring}"
        yodack_add_dm_allow "${allow_list}"
        yodack_add_dm_deny "${deny_list}"
        yodack_add_section_end

        echo "$@"
}

yodack_parse_argv_action_generic () {
        set -- $@

        stop=0
        action=""
        while [ $# -gt 0 ] && [ "$stop" -eq 0 ]; do
                case "$1" in
                        "*."|"*;")
                                stop=1
                                ;;
                        *)
                                action="${action}$1 "
                                ;;
                esac
                shift
        done

        yodack_add_action "$(echo "${action}" | sed -e "s, \$,," -e "s/[        ]/-/g")"
        echo "$@"
}

yodack_need_help () {
        set -- $@

        while [ $# -gt 0 ]; do
                case "$1" in
                        --help|-h|-?|help)
                                return 0
                                ;;
                esac
                shift
        done
        return 1
}

yodack_parse_argv () {
        argv="$@"

        if [ -z "${argv}" ]; then
                yodack_fatal "Parameters. Give them, you must."
        fi

        if yodack_need_help "$argv"; then
                usage
        fi

        argv=$(yodack_parse_argv_archive "${argv}")

        while [ ! -z "${argv}" ]; do
                argv=$(yodack_parse_argv_action "${argv}")
        done
}

## --- Verification, signing & upload --- ##

yodack_verify () {
        if command -v dialog >/dev/null 2>/dev/null; then
                dialog --backtitle "Ye Olde Debian Archive Control Kit" \
                       --title "Verify the commands, you must" \
                       --yes-label "Do" \
                       --no-label "Do Not" \
                       --no-collapse \
                       --defaultno \
                       --yesno "$(cat ${yodack_out})" 0 0
                r=$?
        else
                whiptail --backtitle "Ye Olde Debian Archive Control Kit" \
                         --title "Verify the commands, you must" \
                         --ok-button "Do" \
                         --cancel-button "Do Not" \
                         --defaultno \
                         --yesno "$(cat ${yodack_out})" 0 0
                r=$?
        fi
        clear
        return $r
}

yodack_upload () {
        archives="$(grep "^Archive: " "${yodack_out}" | sed -e "s,Archive:,,g")"
        for archive in $archives; do
                yodack_upload_to "${archive}" "${yodack_final}"
        done
}

yodack_prettify () {
        t="$(mktemp)"
        sed '/./,/^$/!d' < "${yodack_out}" >"${t}"
        mv -f "${t}" "${yodack_out}"
}

yodack_sign () {
        gpg_params="-q -o ${yodack_final} --clearsign ${yodack_out}"
        if [ ! -z "${DEBSIGN_KEYID}" ]; then
                gpg_params="-u ${DEBSIGN_KEYID} ${gpg_params}"
        fi
        if [ ! -z "$GPG_AGENT_INFO" ]; then
                if gpg --batch ${gpg_params} 2>/dev/null; then
                        return
                fi
        fi
        gpg ${gpg_params}
}

yodack_upload_to () {
        if ! command -v "yodack_upload_to_$(yodack_target_sanitise $1)" >/dev/null 2>/dev/null; then
                yodack_fatal "Upload to '$1', how to I know not."
        fi
        "yodack_upload_to_$(yodack_target_sanitise $1)" "$2"
}

## -- MAIN PROGRAM -- ##

for cfg in "/etc/yodack.conf" "$HOME/.yodack.conf" "${YODACK_CONF}"; do
        if [ -e "${cfg}" ]; then
                . "${cfg}"
        fi
done

yodack_parse_argv "$@"
#yodack_add_comments
yodack_prettify

if [ -z "${YODACK_TEST}" ] && ! yodack_verify; then
        yodack_fatal "Hmm. Disturbance in the archive, I feel."
fi

yodack_sign

yodack_upload
